language: node_js

sudo: false

notifications:
  email:
  - yiminghe@gmail.com

node_js:
- 10.15.0

script:
- |
    if [ "$TEST_TYPE" = test ]; then
      npm test
    else
      npm run $TEST_TYPE
    fi
env:
  matrix:
  - TEST_TYPE=test
  - TEST_TYPE=coverage
